#!/usr/bin/env python3
"""
Test script for markdown table fixing functionality.

This script demonstrates the automatic table fixing feature that corrects
incomplete markdown tables generated by DeepSeek OCR.
"""

from deepseek_ocr_converter import DeepSeekOCRConverter


def test_table_fix():
    """Test the markdown table fixing functionality."""
    
    # Sample markdown with incomplete tables (missing separator lines)
    incomplete_markdown = """## Financial Report

### Assets Table

| Asset Type | 2023 | 2022 | 2021 |
| Cash | 1,000 | 900 | 800 |
| Investments | 5,000 | 4,500 | 4,000 |
| Property | 10,000 | 9,500 | 9,000 |

### Liabilities Table

| Liability Type | 2023 | 2022 | 2021 |
| Loans | 2,000 | 2,200 | 2,400 |
| Bonds | 3,000 | 3,100 | 3,200 |

### Summary

| Total | 2023 | 2022 | 2021 |
| Assets | 16,000 | 14,900 | 13,800 |
| Liabilities | 5,000 | 5,300 | 5,600 |
| Net Worth | 11,000 | 9,600 | 8,200 |
"""

    print("=" * 80)
    print("Testing Markdown Table Fixing")
    print("=" * 80)
    print()
    
    print("ORIGINAL MARKDOWN (with incomplete tables):")
    print("-" * 80)
    print(incomplete_markdown)
    print()
    
    # Create converter instance
    converter = DeepSeekOCRConverter()
    
    # Fix the tables
    fixed_markdown = converter._fix_markdown_tables(incomplete_markdown)
    
    print("FIXED MARKDOWN (with separator lines added):")
    print("-" * 80)
    print(fixed_markdown)
    print()
    
    # Count the number of fixes
    original_lines = incomplete_markdown.count('\n')
    fixed_lines = fixed_markdown.count('\n')
    separators_added = fixed_lines - original_lines
    
    print("=" * 80)
    print(f"✓ Added {separators_added} table separator line(s)")
    print(f"  Original: {original_lines} lines")
    print(f"  Fixed: {fixed_lines} lines")
    print("=" * 80)
    
    # Verify the fix
    assert '|---|---|---|---|' in fixed_markdown, "Separator lines should be added"
    assert fixed_markdown.count('|---|---|---|---|') == 3, "Should have 3 separator lines"
    
    print()
    print("✓ All tests passed!")
    print()


if __name__ == "__main__":
    test_table_fix()

